apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: empathy-chatbot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: empathy-chatbot-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75 # If average CPU goes above 75%, Kubernetes will add more pods
