---
- name: Ensure Kubernetes namespace exists (default)
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: default
    state: present

- name: Deploy Chatbot Application
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/deployment.yaml"

- name: Expose Chatbot Service
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/service.yaml"

- name: Apply Horizontal Pod Autoscaler
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/hpa.yaml"
